import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import RootProviders from "../components/providers/RootProviders.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Expense Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <ClerkProvider>
        <html lang="en" className="dark" style={{ colorScheme: "dark" }}>
          <body className={inter.className}>
            <RootProviders>{children}</RootProviders>
          </body>
        </html>
      </ClerkProvider>
  );
}
